Improve scripts.
Update mvn deploy syntax.
Add additional sanity checks.

diff --git a/distribution/publish-snapshot b/distribution/publish-snapshot
--- a/distribution/publish-snapshot
+++ b/distribution/publish-snapshot
@@ -21,7 +21,10 @@ echo "================================================================="
 user_continue
 
 # Build snapshot jars
-./mvn_cmd clean
+if ! ./mvn_cmd clean; then
+  echo "maven clean command failed, check your environment"
+  exit
+fi
 mvn package -Dmaven.javadoc.skip=true -B -V
 
 # Pull latest from the maven repo
@@ -30,7 +33,7 @@ git pull
 popd
 
 # Deploy the artifact to the maven repo
-mvn deploy -DskipTests -DaltDeploymentRepository=snapshot::default::file://${REPO_PATH}
+mvn deploy -DskipTests -DaltDeploymentRepository=snapshot::file://${REPO_PATH}
 
 # Push changes to the maven repo
 pushd ${REPO_PATH}
