Detect and install missing binary dependencies.

diff --git a/.travis/deploy-snapshot b/.travis/deploy-snapshot
--- a/.travis/deploy-snapshot
+++ b/.travis/deploy-snapshot
@@ -29,7 +29,17 @@ if [[ "$VERSION" != *-SNAPSHOT ]]; then
 fi
 
 # Install git binary
-yum install -y git
+if ! command -v git &> /dev/null
+then
+  if command -v apt-get &> /dev/null
+    apt-get update && apt-get install -y git
+  elif command -v yum &> /dev/null
+    yum install -y git
+  else
+    echo "git could not be installed"
+    exit 1
+  fi
+fi
 
 SHA=`git rev-parse --verify HEAD`
 echo "Publishing snapshot jar for revision ${SHA}"
diff --git a/.travis/docker-cmds b/.travis/docker-cmds
--- a/.travis/docker-cmds
+++ b/.travis/docker-cmds
@@ -7,6 +7,19 @@ else
   MVN_CMD="mvn"
 fi
 
+# Install patch binary
+if ! command -v patch &> /dev/null
+then
+  if command -v apt-get &> /dev/null
+    apt-get update && apt-get install -y patch
+  elif command -v yum &> /dev/null
+    yum install -y patch
+  else
+    echo "patch could not be installed"
+    exit 1
+  fi
+fi
+
 # execute maven in docker
 ${MVN_CMD} install -Dmaven.javadoc.skip=true -B -V
 ret_code=$?
